//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownsIntranetApps.Entity.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer1
    {
        public int ID { get; set; }
        public string CutomerName { get; set; }
        public string Contact { get; set; }
        public string Position { get; set; }
        public string Phonenumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BillingContact { get; set; }
        public string BillingEmail { get; set; }
        public string BillingPhone { get; set; }
        public string TaxExemptNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zip { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingCity { get; set; }
        public Nullable<int> ShippingStateId { get; set; }
        public string ShippingZip { get; set; }
        public string TaxJurisdiction { get; set; }
        public string TaxClassification { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsShippingSameAsAddress { get; set; }
    }
}
