//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownsIntranetApps.Entity.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_TaxClassification
    {
        public int ID { get; set; }
        public Nullable<bool> Regular { get; set; }
        public Nullable<bool> Manufacturing { get; set; }
        public Nullable<bool> Government { get; set; }
        public Nullable<bool> Resale { get; set; }
        public Nullable<bool> Farming { get; set; }
        public Nullable<bool> OutofState { get; set; }
    }
}
