//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownsIntranetApps.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        public int ID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SerialNumberRange { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
        public string PartManual { get; set; }
        public string ListPrice { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual company company { get; set; }
    }
}
